language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.3
  - DJANGO_VERSION=1.4.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install . --use-mirrors
script: python setup.py test
branches:
  only:
    - master
