language: python

python:
  - "2.6"

env:
  - TOXENV=py26-1.3.X,py27-1.3.X
  - TOXENV=py26-1.4.X,py27-1.4.X
  - TOXENV=py26-1.5.X,py27-1.5.X
  - TOXENV=py26-trunk,py27-trunk

install:
  - pip install tox --use-mirrors

script:
    - tox

branches:
  only:
    - master

matrix:
  allow_failures:
    - env: TOXENV=py26-trunk,py27-trunk